apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: ibmcase-image-policy
spec:
  repositories:
  # GreenCompute and other Docker Hub Images
  - name: docker.io/*
    policy:
      va:
        enabled: false
  # Kafka
  - name: gcr.io/*
    policy:
      va:
        enabled: false
